### ISSUE TITLE
Bodega name

### ISSUE THREAD

**Issue by tommens** [mehdigolzadeh/BoDeGa#12]
Hello all, I checked on github and there is a huge number of projects (and probably tools) called bodega. Perhaps not very surprising now that I come to think of it. Perhaps we should consider renaming the tool at some point?

**Comment by mehdigolzadeh** [comment]
Really??? Its also the name of a nightclub in brussels :))
How about **botector**?

**Comment by AlexandreDecan** [comment]
I suggest to keep Bodega for the research prototype of the paper, since (1) it will not be distributed on PyPI so name collision is not an issue; (2) it is unlikely that someone tries Bodega without having read the paper (so it's not an easy not to be easily discoverable because of the name). 

If at some point, we come up with a brand new version, feature-complete, of bodega, we can still decide either to rename the tool or the repository, or simply to distribute it as a new project (the latter has my preference).

**Comment by tommens** [comment]
I have some ideas, but I will not start proposing all possible names through these issue comments (since it is visible to anyone that wants to see it), and as Alex suggested, for now it is not yet needed. Therefore we can close the discussion for now (at least on GitHub) and revive it perhaps at some later point whenever it becomes relevant again.
